version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.ip_local_port_range: "1024 65535"
      net.ipv4.tcp_fin_timeout: 30
      net.ipv4.tcp_keepalive_time: 300
      net.ipv4.tcp_tw_reuse: 1
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
